{% set version = "8.0.5.39" %}

package:
  name: cudnn
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/redist/cudnn/v{{ ".".join(version.split(".")[:3]) }}/cudnn-{{ cuda_compiler_version }}-linux-ppc64le-v{{ version }}.tgz  # [ppc64le]
  sha256: ce128ea090b05e36d00ffe921e45982ca10e8207e40cfc2e0067d0f62d9b36f9  # [ppc64le and cuda_compiler_version == "10.2"]

build:
  number: 2
  skip: True   # [(not ppc64le) or (cuda_compiler_version != "10.2")]
  script_env:
    # for some reason /usr/local/cuda is not added to $PATH in ppc64le's docker image
    - CUDA_HOME  # [ppc64le]
  script:
    - mkdir -p $PREFIX/include               # [unix]
    - cd targets/ppc64le-linux          # [ppc64le]
    - cp include/cudnn*.h $PREFIX/include/    # [unix]
    - mkdir -p $PREFIX/lib                   # [unix]
    - mv lib64/libcudnn*.so* $PREFIX/lib/     # [linux64]
    - mv lib/libcudnn*.so* $PREFIX/lib/       # [ppc64le]
    - mkdir %LIBRARY_INC%                    # [win]
    - copy %SRC_DIR%\\include\\cudnn*.h %LIBRARY_INC%\\     # [win]
    - mkdir %LIBRARY_LIB%                    # [win]
    - copy %SRC_DIR%\\lib\\x64\\cudnn*.lib %LIBRARY_LIB%\\  # [win]
    - mkdir %LIBRARY_BIN%                    # [win]
    - copy %SRC_DIR%\\bin\\cudnn*_8.dll %LIBRARY_BIN%\\     # [win]
  ignore_run_exports_from:
    - {{ compiler('c') }}    # [linux]
    - {{ compiler('cuda') }}
  run_exports:
    - {{ pin_subpackage('cudnn') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - sysroot_linux-64 2.17  # [linux]
  host:
  run:
    # Only GCC_3.0 or older symbols present
    - libgcc-ng >=3.0     # [linux]
    # Only GLIBCXX_3.4 or older symbols present
    - libstdcxx-ng >=3.4  # [linux]
    - cudatoolkit {{ cuda_compiler_version }}  # [cuda_compiler_version == "10.2"]
    - cudatoolkit 11.*  # [cuda_compiler_version == "11.2"]
  run_constrained:
    # Only GLIBC_2.17 or older symbols present
    - __glibc >=2.17      # [ppc64le]

test:
  requires:
    - {{ compiler('c') }}  # [ppc64le]
  files:
    - test_elf_integrity.c  # [ppc64le]
  commands:
    - if not exist %LIBRARY_INC%/cudnn.h exit 1        # [win]
    - if not exist %LIBRARY_INC%/cudnn_adv_train.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%/cudnn.lib exit 1      # [win]
    - if not exist %LIBRARY_LIB%/cudnn_adv_train.lib exit 1      # [win]
    - if not exist %LIBRARY_BIN%/cudnn64_8.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%/cudnn_adv_train64_8.dll exit 1  # [win]
    - test -f $PREFIX/include/cudnn.h                  # [linux]
    - test -f $PREFIX/include/cudnn_adv_train.h        # [linux]
    - test -f $PREFIX/lib/libcudnn.so                  # [linux]
    - test -f $PREFIX/lib/libcudnn_adv_train.so        # [linux]
    - ${GCC} test_elf_integrity.c -std=c99 -Werror -ldl -o test_elf_integrity  # [ppc64le]
    - test_elf_integrity $PREFIX/lib/libcudnn.so       # [ppc64le]

about:
  home: https://developer.nvidia.com/cudnn
  license: LicenseRef-cuDNN-Software-License-Agreement
  license_file: targets/ppc64le-linux/NVIDIA_SLA_cuDNN_Support.txt  # [ppc64le]
  license_file: NVIDIA_SLA_cuDNN_Support.txt  # [not ppc64le]
  license_url: https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
  summary: "NVIDIA's cuDNN deep neural network acceleration library"
  description: |
    NVIDIA CUDA Deep Neural Network (cuDNN) is a GPU-accelerated library of
    primitives for deep neural networks. It provides highly tuned
    implementations of routines arising frequently in DNN applications.

    License Agreements:- The packages are governed by the NVIDIA cuDNN
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuDNN EULA -
    https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
  doc_url: https://docs.nvidia.com/deeplearning/cudnn/
  dev_url: https://developer.nvidia.com/rdp/cudnn-download

extra:
  recipe-maintainers:
    - leofang
    - kkraus14
