{% set version = "9.8.0.87" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: cudnn
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/{{ platform }}/cudnn-{{ platform }}-{{ version }}_cuda11-archive.{{ extension }}  # [(cuda_compiler_version or "").startswith("11")]
  url: https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/{{ platform }}/cudnn-{{ platform }}-{{ version }}_cuda12-archive.{{ extension }}  # [(cuda_compiler_version or "").startswith("12")]
  sha256: cf4dfaef8311d987d640a322f668cd5240ac3e5302abe9617dd991b5b2532758  # [linux64 and (cuda_compiler_version or "").startswith("11")]
  sha256: 321b9b33bb1287404d93d5672d352f16feabc4b220ac6ae0b86e4b27f257dcf4  # [linux64 and (cuda_compiler_version or "").startswith("12")]
  sha256: 8ff117715fb3323032d1b489880117556ad8b5e57a9060143f0cb72384db7710  # [aarch64 and (cuda_compiler_version or "").startswith("11")]
  sha256: 22f62f474f0cbb35bef540adb1d841da63c9cd3df76b3c4e43010f436b2cd85c  # [aarch64 and (cuda_compiler_version or "").startswith("12")]
  sha256: b2995837e6b9a5b3816a0cd90480769cd4280f965c2ef0848debf029f391ca8f  # [win and (cuda_compiler_version or "").startswith("11")]
  sha256: d8a23705e3884b137b7e05449fb2b61bfa524e7cfc3fda80743d633f423c6ce4  # [win and (cuda_compiler_version or "").startswith("12")]

build:
  number: 0
  skip: True  # [cuda_compiler_version in ("None", None)]
  # Disable binary relocation to workaround patchelf issue
  # xref: https://github.com/NixOS/patchelf/issues/492
  binary_relocation: false
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
    - libcublas-dev  # [(cuda_compiler_version or "").startswith("12")]
  run_exports:
    - {{ pin_subpackage('cudnn') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - patchelf >=0.12  # [linux]
  host:
    - cuda-version {{ cuda_compiler_version }}
    # For Windows, zlib is statically linked into CUDNN since version 9.2
    # https://docs.nvidia.com/deeplearning/cudnn/latest/release-notes.html#cudnn-9-2-0
    # For Linux, zlib remains a dynamically linked dependency
    - zlib  # [not win]
  run:
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    - cudatoolkit       # [(cuda_compiler_version or "").startswith("11")]
    - cuda-nvrtc        # [(cuda_compiler_version or "").startswith("12")]
    - libcublas         # [(cuda_compiler_version or "").startswith("12")]
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - {{ compiler('c') }}  # [linux]
  files:
    - test_load_elf.c      # [linux]
  commands:
    - if not exist %LIBRARY_INC%/cudnn.h exit 1                       # [win]
    - if not exist %LIBRARY_INC%/cudnn_adv.h exit 1                   # [win]
    - if not exist %LIBRARY_LIB%/cudnn.lib exit 1                     # [win]
    - if not exist %LIBRARY_LIB%/cudnn_adv.lib exit 1                 # [win]
    - if not exist %LIBRARY_BIN%/cudnn64_9.dll exit 1                 # [win]
    - if not exist %LIBRARY_BIN%/cudnn_adv64_9.dll exit 1             # [win]
    - test -f $PREFIX/include/cudnn.h                                 # [linux]
    - test -f $PREFIX/include/cudnn_adv.h                             # [linux]
    - test -f $PREFIX/lib/libcudnn.so                                 # [linux]
    - test -f $PREFIX/lib/libcudnn_adv.so                             # [linux]
    - ${GCC} test_load_elf.c -std=c99 -Werror -ldl -o test_load_elf   # [linux]
    - for f in $PREFIX/lib/libcudnn*.so; do ./test_load_elf $f; done  # [linux]

about:
  home: https://developer.nvidia.com/cudnn
  license: LicenseRef-cuDNN-Software-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
  summary: "NVIDIA's cuDNN deep neural network acceleration library"
  description: |
    NVIDIA CUDA Deep Neural Network (cuDNN) is a GPU-accelerated library of
    primitives for deep neural networks. It provides highly tuned
    implementations of routines arising frequently in DNN applications.

    License Agreements:- The packages are governed by the NVIDIA cuDNN
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuDNN EULA -
    https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
  doc_url: https://docs.nvidia.com/deeplearning/cudnn/
  dev_url: https://developer.nvidia.com/rdp/cudnn-download

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - billysuh7
    - adibbley
    - bdice
    - jakirkham
    - vyasr
