conda_forge_output_validation: true
provider:
  linux_aarch64: default
# NOTE: For binary redists os_version should match oldest supported glibc
os_version:
  linux_64: cos7
  linux_aarch64: cos7
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
