conda_forge_output_validation: true
provider:
  linux_ppc64le: default
  linux_aarch64: default
os_version:
  linux_64: cos7
bot:
  abi_migration_branches:
  - ppc64le
github:
  branch_name: main
  tooling_branch_name: main
